// This file was generated by liblab | https://liblab.com/

package channels

import (
	"encoding/json"
)

type ApnsTokenResponse struct {
	// (Optional) The bundle identifier of the application that is registering this token. Use this field to override the default identifier specified in the projects APNs integration.
	AppId       *string `json:"app_id,omitempty" pattern:"^[a-zA-Z0-9]+(.[a-zA-Z0-9]+)*$"`
	CreatedAt   *string `json:"created_at,omitempty" required:"true"`
	DeviceToken *string `json:"device_token,omitempty" required:"true" minLength:"64"`
	DiscardedAt *string `json:"discarded_at,omitempty"`
	Id          *string `json:"id,omitempty" required:"true"`
	// (Optional) The APNs environment the token is registered for. If none is provided we assume the token is used in `production`.
	InstallationId *ApnsTokenResponseInstallationId `json:"installation_id,omitempty"`
	UpdatedAt      *string                          `json:"updated_at,omitempty"`
	touched        map[string]bool
}

func (a *ApnsTokenResponse) GetAppId() *string {
	if a == nil {
		return nil
	}
	return a.AppId
}

func (a *ApnsTokenResponse) SetAppId(appId string) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["AppId"] = true
	a.AppId = &appId
}

func (a *ApnsTokenResponse) SetAppIdNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["AppId"] = true
	a.AppId = nil
}

func (a *ApnsTokenResponse) GetCreatedAt() *string {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *ApnsTokenResponse) SetCreatedAt(createdAt string) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["CreatedAt"] = true
	a.CreatedAt = &createdAt
}

func (a *ApnsTokenResponse) SetCreatedAtNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["CreatedAt"] = true
	a.CreatedAt = nil
}

func (a *ApnsTokenResponse) GetDeviceToken() *string {
	if a == nil {
		return nil
	}
	return a.DeviceToken
}

func (a *ApnsTokenResponse) SetDeviceToken(deviceToken string) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["DeviceToken"] = true
	a.DeviceToken = &deviceToken
}

func (a *ApnsTokenResponse) SetDeviceTokenNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["DeviceToken"] = true
	a.DeviceToken = nil
}

func (a *ApnsTokenResponse) GetDiscardedAt() *string {
	if a == nil {
		return nil
	}
	return a.DiscardedAt
}

func (a *ApnsTokenResponse) SetDiscardedAt(discardedAt string) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["DiscardedAt"] = true
	a.DiscardedAt = &discardedAt
}

func (a *ApnsTokenResponse) SetDiscardedAtNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["DiscardedAt"] = true
	a.DiscardedAt = nil
}

func (a *ApnsTokenResponse) GetId() *string {
	if a == nil {
		return nil
	}
	return a.Id
}

func (a *ApnsTokenResponse) SetId(id string) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["Id"] = true
	a.Id = &id
}

func (a *ApnsTokenResponse) SetIdNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["Id"] = true
	a.Id = nil
}

func (a *ApnsTokenResponse) GetInstallationId() *ApnsTokenResponseInstallationId {
	if a == nil {
		return nil
	}
	return a.InstallationId
}

func (a *ApnsTokenResponse) SetInstallationId(installationId ApnsTokenResponseInstallationId) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["InstallationId"] = true
	a.InstallationId = &installationId
}

func (a *ApnsTokenResponse) SetInstallationIdNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["InstallationId"] = true
	a.InstallationId = nil
}

func (a *ApnsTokenResponse) GetUpdatedAt() *string {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *ApnsTokenResponse) SetUpdatedAt(updatedAt string) {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["UpdatedAt"] = true
	a.UpdatedAt = &updatedAt
}

func (a *ApnsTokenResponse) SetUpdatedAtNil() {
	if a.touched == nil {
		a.touched = map[string]bool{}
	}
	a.touched["UpdatedAt"] = true
	a.UpdatedAt = nil
}

func (a ApnsTokenResponse) MarshalJSON() ([]byte, error) {
	data := make(map[string]any)

	if a.touched["AppId"] && a.AppId == nil {
		data["app_id"] = nil
	} else if a.AppId != nil {
		data["app_id"] = a.AppId
	}

	if a.touched["CreatedAt"] && a.CreatedAt == nil {
		data["created_at"] = nil
	} else if a.CreatedAt != nil {
		data["created_at"] = a.CreatedAt
	}

	if a.touched["DeviceToken"] && a.DeviceToken == nil {
		data["device_token"] = nil
	} else if a.DeviceToken != nil {
		data["device_token"] = a.DeviceToken
	}

	if a.touched["DiscardedAt"] && a.DiscardedAt == nil {
		data["discarded_at"] = nil
	} else if a.DiscardedAt != nil {
		data["discarded_at"] = a.DiscardedAt
	}

	if a.touched["Id"] && a.Id == nil {
		data["id"] = nil
	} else if a.Id != nil {
		data["id"] = a.Id
	}

	if a.touched["InstallationId"] && a.InstallationId == nil {
		data["installation_id"] = nil
	} else if a.InstallationId != nil {
		data["installation_id"] = a.InstallationId
	}

	if a.touched["UpdatedAt"] && a.UpdatedAt == nil {
		data["updated_at"] = nil
	} else if a.UpdatedAt != nil {
		data["updated_at"] = a.UpdatedAt
	}

	return json.Marshal(data)
}

func (a ApnsTokenResponse) String() string {
	jsonData, err := json.MarshalIndent(a, "", "  ")
	if err != nil {
		return "error converting struct: ApnsTokenResponse to string"
	}
	return string(jsonData)
}

// (Optional) The APNs environment the token is registered for. If none is provided we assume the token is used in `production`.
type ApnsTokenResponseInstallationId string

const (
	APNS_TOKEN_RESPONSE_INSTALLATION_ID_DEVELOPMENT ApnsTokenResponseInstallationId = "development"
	APNS_TOKEN_RESPONSE_INSTALLATION_ID_PRODUCTION  ApnsTokenResponseInstallationId = "production"
)
