// This file was generated by liblab | https://liblab.com/

package channels

import (
	"encoding/json"
)

type ExpoTokenResponse struct {
	CreatedAt   *string `json:"created_at,omitempty" required:"true"`
	DeviceToken *string `json:"device_token,omitempty" required:"true" minLength:"1"`
	DiscardedAt *string `json:"discarded_at,omitempty"`
	Id          *string `json:"id,omitempty" required:"true"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	touched     map[string]bool
}

func (e *ExpoTokenResponse) GetCreatedAt() *string {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *ExpoTokenResponse) SetCreatedAt(createdAt string) {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["CreatedAt"] = true
	e.CreatedAt = &createdAt
}

func (e *ExpoTokenResponse) SetCreatedAtNil() {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["CreatedAt"] = true
	e.CreatedAt = nil
}

func (e *ExpoTokenResponse) GetDeviceToken() *string {
	if e == nil {
		return nil
	}
	return e.DeviceToken
}

func (e *ExpoTokenResponse) SetDeviceToken(deviceToken string) {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["DeviceToken"] = true
	e.DeviceToken = &deviceToken
}

func (e *ExpoTokenResponse) SetDeviceTokenNil() {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["DeviceToken"] = true
	e.DeviceToken = nil
}

func (e *ExpoTokenResponse) GetDiscardedAt() *string {
	if e == nil {
		return nil
	}
	return e.DiscardedAt
}

func (e *ExpoTokenResponse) SetDiscardedAt(discardedAt string) {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["DiscardedAt"] = true
	e.DiscardedAt = &discardedAt
}

func (e *ExpoTokenResponse) SetDiscardedAtNil() {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["DiscardedAt"] = true
	e.DiscardedAt = nil
}

func (e *ExpoTokenResponse) GetId() *string {
	if e == nil {
		return nil
	}
	return e.Id
}

func (e *ExpoTokenResponse) SetId(id string) {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["Id"] = true
	e.Id = &id
}

func (e *ExpoTokenResponse) SetIdNil() {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["Id"] = true
	e.Id = nil
}

func (e *ExpoTokenResponse) GetUpdatedAt() *string {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}

func (e *ExpoTokenResponse) SetUpdatedAt(updatedAt string) {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["UpdatedAt"] = true
	e.UpdatedAt = &updatedAt
}

func (e *ExpoTokenResponse) SetUpdatedAtNil() {
	if e.touched == nil {
		e.touched = map[string]bool{}
	}
	e.touched["UpdatedAt"] = true
	e.UpdatedAt = nil
}

func (e ExpoTokenResponse) MarshalJSON() ([]byte, error) {
	data := make(map[string]any)

	if e.touched["CreatedAt"] && e.CreatedAt == nil {
		data["created_at"] = nil
	} else if e.CreatedAt != nil {
		data["created_at"] = e.CreatedAt
	}

	if e.touched["DeviceToken"] && e.DeviceToken == nil {
		data["device_token"] = nil
	} else if e.DeviceToken != nil {
		data["device_token"] = e.DeviceToken
	}

	if e.touched["DiscardedAt"] && e.DiscardedAt == nil {
		data["discarded_at"] = nil
	} else if e.DiscardedAt != nil {
		data["discarded_at"] = e.DiscardedAt
	}

	if e.touched["Id"] && e.Id == nil {
		data["id"] = nil
	} else if e.Id != nil {
		data["id"] = e.Id
	}

	if e.touched["UpdatedAt"] && e.UpdatedAt == nil {
		data["updated_at"] = nil
	} else if e.UpdatedAt != nil {
		data["updated_at"] = e.UpdatedAt
	}

	return json.Marshal(data)
}

func (e ExpoTokenResponse) String() string {
	jsonData, err := json.MarshalIndent(e, "", "  ")
	if err != nil {
		return "error converting struct: ExpoTokenResponse to string"
	}
	return string(jsonData)
}
